affinity: {}
cameras:
  camera1: null
workingDir:
  dspath: /opt/nvidia/deepstream/deepstream-5.0/sources/python/apps/deepstream-facedetect
  rtsppath: /opt/python/notebooks
command:
  apparg1: rtsp://videoanalytics-video-analytics-pipeline-rtsp-input1:8554/input
  #apparg2: rtsp://videoanalytics-video-analytics-pipeline-rtsp-input2:8554/input
  #apparg3: rtsp://videoanalytics-video-analytics-pipeline-rtsp-input3:8554/input
  #apparg4: rtsp://videoanalytics-video-analytics-pipeline-rtsp-input4:8554/input
  #apparg5: rtsp://videoanalytics-video-analytics-pipeline-rtsp-input5:8554/input
  #apparg6: rtsp://videoanalytics-video-analytics-pipeline-rtsp-input6:8554/input
  #apparg7: rtsp://videoanalytics-video-analytics-pipeline-rtsp-input7:8554/input
  #apparg8: rtsp://videoanalytics-video-analytics-pipeline-rtsp-input8:8554/input
  #apparg9: rtsp://videoanalytics-video-analytics-pipeline-rtsp-input9:8554/input
  #apparg10: rtsp://videoanalytics-video-analytics-pipeline-rtsp-input10:8554/input
  #apparg11: rtsp://videoanalytics-video-analytics-pipeline-rtsp-input11:8554/input
  #apparg12: rtsp://videoanalytics-video-analytics-pipeline-rtsp-input12:8554/input
  #apparg13: rtsp://videoanalytics-video-analytics-pipeline-rtsp-input13:8554/input
  #apparg14: rtsp://videoanalytics-video-analytics-pipeline-rtsp-input14:8554/input
  #apparg15: rtsp://videoanalytics-video-analytics-pipeline-rtsp-input15:8554/input
  #apparg16: rtsp://videoanalytics-video-analytics-pipeline-rtsp-input16:8554/input

  appname: deepstream_facedetect.py
  rtspappname: vid2rtspso.py
fullnameOverride: ""

image:
  rtspserver: 
    repository: gcr.io/qp-tmeg-bu-2020-11
    name: rtspserver
    tag: v1
  dsapp:
    repository: gcr.io/qp-tmeg-bu-2020-11
    name: dsapp
    tag: v1
  webui:
    repository: anguda
    name: ant-media 
    tag: 1.0

imageConfig:
  pullPolicy: IfNotPresent

# imagePullSecrets:
# - name: nvidia-ngc-key
ingress:
  annotations: {}
  enabled: false
  hosts:
  - host: chart-example.local
    paths: []
  tls: []
nameOverride: ""
nodeSelector: {}
replicaCount: 1
resources: {}
service:
  nodePort: 31113
  port: 80
  type: NodePort
  webuiPort: 5080
  webuinodePort: 31115
  rtspPort: 8554
  rtspnodePort: 31117
mountpath: /opt/nvidia/deepstream/deepstream-5.0/sources/python/apps/deepstream-facedetect/facedetectir/config_infer_primary_facedetectir.txt
subpath: config_infer_primary_facedetectir.txt


streammountPath: /opt/python/notebooks/streams

tolerations: []

apis:
- name: input1
  command: streams/Sub1.avi
  argwidth: 640
  argheight: 480
  nodePort: 31117

