apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "video-analytics-pipeline.fullname" . }}
  labels:
{{ include "video-analytics-pipeline.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "video-analytics-pipeline.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "video-analytics-pipeline.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    # {{- with .Values.imagePullSecrets }}
    #   imagePullSecrets:
    #     {{- toYaml . | nindent 8 }}
    # {{- end }}
      containers:
        - name: "{{ .Chart.Name }}-1"
          image: "{{ $root.Values.image.dsapp.repository }}/{{ $root.Values.image.dsapp.name }}:{{ $root.Values.image.dsapp.tag }}"
          imagePullPolicy: {{ .Values.imageConfig.pullPolicy }}
          workingDir: "{{ .Values.workingDir.dspath }}"
          command: ["tail", "-f"]
          #command: ["python3", {{ .Values.command.appname }}]
          #command: ["nvidia-smi"]
          #args: [{{ .Values.command.apparg1}}] 
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          ports: 
            - name: http
              containerPort: 8554
              protocol: TCP
          volumeMounts:
            - name: ipmount
              mountPath: {{ .Values.mountpath}}
              subPath: {{ .Values.subpath }}
      volumes:
        - name: ipmount
          configMap:
            name: {{ include "video-analytics-pipeline.fullname" . }}-configmap	  
{{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "video-analytics-pipeline.fullname" . }}-webui
  labels:
    name: {{ include "video-analytics-pipeline.fullname" . }}-webui
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: {{ include "video-analytics-pipeline.fullname" . }}-webui
  template:
    metadata:
      labels:
        name: {{ include "video-analytics-pipeline.fullname" . }}-webui
    spec:
      containers:
        - name: "{{ .Chart.Name }}-webui-1"
          image: "{{ .Values.image.webui.repository }}/{{ .Values.image.webui.name }}:{{ .Values.image.webui.tag }}"
          imagePullPolicy: {{ .Values.imageConfig.pullPolicy }}
          env:
          - name: NODE_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: DS_PORT
            value: "{{ .Values.service.nodePort }}"
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "bash /tmp/serverstart.sh; cp -r /tmp/play.html /usr/local/antmedia/webapps/WebRTCApp/play.html"]
          resources: {}
          volumeMounts:
          - mountPath: /tmp/play.html
            name: play
            subPath: play.html
          ports:
            - name: http
              containerPort: {{ .Values.service.webuiPort }}
              protocol: TCP
      volumes:
      - configMap:
          defaultMode: 420
          name: {{ include "video-analytics-pipeline.fullname" . }}-webui-configmap
        name: play
---
{{- $root := . }}
{{- range $api := $root.Values.apis }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "video-analytics-pipeline.fullname" $root }}-rtsp-{{ $api.name }}
  labels:
    name: {{ include "video-analytics-pipeline.fullname" $root }}-rtsp-{{ $api.name }}
spec:
  replicas: {{ $root.Values.replicaCount }}
  selector:
    matchLabels:
      name: {{ include "video-analytics-pipeline.fullname" $root }}-rtsp-{{ $api.name }}
  template:
    metadata:
      labels:
        name: {{ include "video-analytics-pipeline.fullname" $root }}-rtsp-{{ $api.name }}
    spec:
      containers:
        - name: "{{ $root.Chart.Name }}-rtsp-1-{{ $api.name }}"
          image: "{{ .Values.image.rtspserver.repository }}/{{ .Values.image.rtspserver.name }}:{{ .Values.image.rtspserver.tag }}"
          imagePullPolicy: {{ $root.Values.imageConfig.pullPolicy }}
          workingDir: "{{ $root.Values.workingDir.rtsppath }}"
          command: ["tail", "-f"]
          #command: ["python3", "{{ $root.Values.command.rtspappname }}","-path", "{{ $api.command}}", "-width", "{{ $api.argwidth}}", "-height", "{{ $api.argheight}}" ]
          resources: {}
          ports:
            - name: http
              containerPort: 8554
              protocol: TCP
          volumeMounts:
            - name: rtsp-stream-mount
              mountPath: {{ $root.Values.streammountPath}}
              readOnly: true
      volumes:
        - name: rtsp-stream-mount
          hostPath:
            path: /abc
            type: DirectoryOrCreate	
---
{{- end }}
