apiVersion: v1
kind: PersistentVolume
metadata:
  name: ds-input-pv
spec:
  storageClassName: ""
  capacity:
    storage: 50Gi
  accessModes:
    - ReadOnlyMany
  claimRef:
    namespace: default
    name: ds-input-pvclaim
  gcePersistentDisk:
    pdName: ds-input-stream
    fsType: ext4
    readOnly: true
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ds-input-pvclaim
spec:
  # Specify "" as the storageClassName so it matches the PersistentVolume's StorageClass.
  # A nil storageClassName value uses the default StorageClass. For details, see
  # https://kubernetes.io/docs/concepts/storage/persistent-volumes/#class-1
  storageClassName: ""
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 50Gi