apiVersion: v1
kind: Service
metadata:
  name: {{ include "video-analytics-pipeline.fullname" . }}
  labels:
{{ include "video-analytics-pipeline.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      nodePort: {{ .Values.service.nodePort }}
  selector:
    app.kubernetes.io/name: {{ include "video-analytics-pipeline.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "video-analytics-pipeline.fullname" . }}-webui
  labels:
    name: {{ include "video-analytics-pipeline.fullname" . }}-webui
spec:
  # type: {{ .Values.service.type }}
  type: LoadBalancer
  ports:
    - port: {{ .Values.service.webuiPort }}
      targetPort: http
      protocol: TCP
      name: http
      nodePort: {{ .Values.service.webuinodePort }}
  selector:
    name: {{ include "video-analytics-pipeline.fullname" . }}-webui
---
{{- $root := . }}
{{- range $api := .Values.apis }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "video-analytics-pipeline.fullname" $root }}-rtsp-{{ $api.name }}
  labels:
    name: {{ include "video-analytics-pipeline.fullname" $root }}-rtsp-{{ $api.name }}
spec:
  type: {{ $root.Values.service.type }}
  ports:
    - port: {{ $root.Values.service.rtspPort }}
      targetPort: http
      protocol: TCP
      name: http
      nodePort: {{ $api.nodePort }}
  selector:
    name: {{ include "video-analytics-pipeline.fullname" $root }}-rtsp-{{ $api.name }}
---
{{- end }}
